# Let new devices join our zigbee network, disable after devices added
permit_join: true
homeassistant: true
mqtt:
  base_topic: zigbee2mqtt/dev
  server: mqtts://host:8883
  user: user
  password: password
# Zigbee Adapter path
serial:
  port: /dev/ttyUSB0
# Enable the Zigbee2MQTT frontend
frontend:
  port: 8080
# Let Zigbee2MQTT generate a new network key on first start
advanced:
  network_key: GENERATE
  rtscts: false
  log_level: warn